SET SERVEROUTPUT ON

CREATE OR REPLACE TRIGGER AuditoriaInsertProducto
    AFTER INSERT OR DELETE OR UPDATE ON PRODUCTO
    FOR EACH ROW
    DECLARE
        V_REGISTRO_OLD VARCHAR2(300);
        V_REGISTRO_NEW VARCHAR2(300);
        V_OPCION NUMBER(1);
    BEGIN
        CASE
        WHEN INSERTING THEN
            V_OPCION:=1;
            V_REGISTRO_OLD:=(NULL);
            V_REGISTRO_NEW:=(:NEW.CODIGO_PROD||' # '||:NEW.PRECIO||' # '||:NEW.DENOMINACION_PRODUCTO||' # '||:NEW.STOCK||' # '||:NEW.NOMBRE_DEPARTAMENTO||' # '||:NEW.DENOMINACION_SECCION||' # '||:NEW.N_CCOMERCIAL);
                
        WHEN UPDATING THEN
            V_OPCION:=2;
            V_REGISTRO_OLD:=(:OLD.CODIGO_PROD||' # '||:OLD.PRECIO||' # '||:OLD.DENOMINACION_PRODUCTO||' # '||:OLD.STOCK||' # '||:OLD.NOMBRE_DEPARTAMENTO||' # '||:OLD.DENOMINACION_SECCION||' # '||:OLD.N_CCOMERCIAL);
            V_REGISTRO_NEW:=(:NEW.CODIGO_PROD||' # '||:NEW.PRECIO||' # '||:NEW.DENOMINACION_PRODUCTO||' # '||:NEW.STOCK||' # '||:NEW.NOMBRE_DEPARTAMENTO||' # '||:NEW.DENOMINACION_SECCION||' # '||:NEW.N_CCOMERCIAL);
                
        WHEN DELETING THEN
            V_OPCION:=3;
            V_REGISTRO_NEW:=(NULL);
            V_REGISTRO_OLD:=(:OLD.CODIGO_PROD||' # '||:OLD.PRECIO||' # '||:OLD.DENOMINACION_PRODUCTO||' # '||:OLD.STOCK||' # '||:OLD.NOMBRE_DEPARTAMENTO||' # '||:OLD.DENOMINACION_SECCION||' # '||:OLD.N_CCOMERCIAL);

        END CASE;
        INSERT INTO AUDITORIA VALUES (USER, TO_DATE((SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') FROM DUAL),'DD/MM/YYYY HH24:MI:SS'), V_OPCION, V_REGISTRO_OLD, V_REGISTRO_NEW);
END AuditoriaInsertProducto;
/
