--Procedimiento 1

CREATE OR REPLACE PROCEDURE VER_EMPLEADO(V_NOMEMP VARCHAR2)
IS 
   V_NUMEMPLEADO CHAR(6);
   V_NOMEMPLEADO VARCHAR2(20);
   V_APLEEIDO1 VARCHAR2(40);
   V_APLEEIDO2 VARCHAR2(40);
   V_DIRECCION VARCHAR2(40);
   V_TELEFONO NUMBER(6);
   V_NTIPOCONTRATO VARCHAR2(40);
BEGIN
   SELECT NUMEMPLEADO, NOMBRE, APELLIDO1, APELLIDO2, DIRECCION, TELEFONO, NOM_TIPO_CONTRATO
   INTO V_NUMEMPLEADO, V_NOMEMPLEADO, V_APLEEIDO1, V_APLEEIDO2, V_DIRECCION, V_TELEFONO, V_NTIPOCONTRATO FROM EMPLEADO WHERE NOMBRE=V_NOMEMP;
   DBMS_OUTPUT.PUT_LINE('Nombre:' || V_NUMEMPLEADO || ' NIF:' ||V_NOMEMPLEADO|| 'Domicilio' ||V_DIRECCION);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('No hemos encontrado al usuario' || V_NOMEMP);
END;
/
